Updatecars
VCET-Driverless/SolecthonWebsite pull request #15
Opened 2023-07-29 14:01 UTC by Aditya-Lawate-codez

added sponsors and changed media page

2023-07-29 17:31 UTC, sharvin18 requested changes
Check the comment in index.html, make necessary changes.

2023-07-29 17:31 UTC, sharvin18 commented on pages/index.html
Please explain this part. Is this the page that redirects the wrong url's? If yes, why is the content in body commented? It has wrong href as well. The content tag in <Head> contains wrong url.

2023-07-30 06:40 UTC, Aditya-Lawate-codez commented on pages/index.html
> If anyone arrives to --> [this page](https://vcet.edu.in/VcetSolecthon/pages/) They see a directories so as to avoid that I created this 404 page

2023-08-12 13:24 UTC, sharvin18 approved these changes
LGTM

2023-08-12 13:24 UTC, merged