Updatespons
VCET-Driverless/SolecthonWebsite pull request #16
Opened 2023-07-29 14:02 UTC by Aditya-Lawate-codez

changed sponsors page and media page

2023-07-29 17:50 UTC, sharvin18 requested changes
Same changes in different branches.
Be careful when you pull from main into your branch.
If changes not needed, just delete them

2023-07-29 17:50 UTC, sharvin18 commented on pages/index.html
Why is the same change reflecting in 2 different branches and pull requests?

2023-07-29 17:50 UTC, sharvin18 commented on images/yt.svg
Why is the same change reflecting in 2 different branches and pull requests?

2023-07-30 06:38 UTC, Aditya-Lawate-codez commented on pages/index.html
1. I dont know why the same changes are reflecting again and again
2. How to delete the changes?

2023-08-12 13:54 UTC, closed without merging